apiVersion: v1
kind: Service
metadata:
  name: projectservice
spec:
  type: ClusterIP
  selector:
    app: projectservice
  ports:
    - name: server
      port: 7000
      targetPort: 7000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectservice
spec:
  selector:
    matchLabels:
      app: projectservice
  template:
    metadata:
      labels:
        app: projectservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
        - name: server
          image: changjjjjjjjj/raffle-project-service:v0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 3550
          env:
            - name: PORT
              value: "7000"
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbHost
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbPort
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbUser
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbPassword
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: dbName
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
      volumes:
        - name: db-secret
          secret:
            defaultMode: 420
            secretName: db-secret
---
